### ISSUE TITLE
Skill Checks aren't working

### ISSUE THREAD

**Issue by Juanfrank** [Ethck/Ethck-s-Downtime-Tracking#11]
Using any Ability Check works fine, but Skill Checks (Acrobatics, Athletics, etc.) aren't. I'm not too sure about Saving Throws since after updating I can't seem to save or change any config (probably related to #10 ).

**Comment by Ethck** [comment]
I can't replicate an issue like this without steps. Can you please provide me a screenshot of the downtime activity? Additionally, can you post the a screenshot of the console (f12 in most browsers to view)?

**Comment by Ethck** [comment]
This is not related to #10. That is a feature request that is currently not implemented.

**Comment by Juanfrank** [comment]
Oh sorry, that was a misinterpretation (I thought you meant output crashed).

For starters, can't get past this screen (wanted to test Checks, Saves and Skill Checks):
![image](https://user-images.githubusercontent.com/2864949/92271474-d946ab80-eeb5-11ea-960d-143dd443ef7b.png)

**Comment by Ethck** [comment]
no worries. After you click the submit button and nothing happens, could you post the error message(s) that are shown in the console? (F12)

**Comment by Ethck** [comment]
Ah, is this a world downtime? (configured through Module settings?)

**Comment by Juanfrank** [comment]
Errors? Ugh...

`<div id="downtime-ethck" class="app window-app form" data-appid="107" style="z-index: 153; width: 600px; left: 585px; top: 0px; height: 992px;">
    <header class="window-header flexrow draggable">
        <h4 class="window-title">Add a Downtime Event</h4>
        <a class="close" title=""><i class="fas fa-times"></i>Close</a>
    </header>

    <section class="window-content"><form autocomplete="off" onsubmit="event.preventDefault();">
    <div style="display:flex; flex-direction:row">
        <div style="width:160px; margin-right: 5px;">
            <img style="height: 160px; width: 160px;" class="file-picker" src="" data-type="image">
        </div>
        <div>
            <label>Name:</label>
            <input type="text" id="name" name="name" value="">
            <label>Description:</label>
            <textarea name="desc" id="desc"></textarea>
        </div>
    </div>
    <fieldset>
    <div class="form-group">
        <label>Ability Checks</label>
        <select name="abiCheck" id="abiCheck">
        
            <option label=" "></option>
            
                <option value="Strength Check" id="str" data-dtype="Boolean">
                Strength
            
            
                </option><option value="Dexterity Check" id="dex" data-dtype="Boolean">
                Dexterity
            
            
                </option><option value="Constitution Check" id="con" data-dtype="Boolean">
                Constitution
            
            
                </option><option value="Intelligence Check" id="int" data-dtype="Boolean">
                Intelligence
            
            
                </option><option value="Wisdom Check" id="wis" data-dtype="Boolean">
                Wisdom
            
            
                </option><option value="Charisma Check" id="cha" data-dtype="Boolean">
                Charisma
            
        
    </option></select>
    </div>
    <div class="form-group">
        <label>Saving Throws</label>
        <select name="saveSelect" id="saveSelect">
        
            <option label=" "></option>
            
                <option vaule="Strength Saving Throw" id="str" data-dtype="Boolean">
                Strength            
            
            
                </option><option vaule="Dexterity Saving Throw" id="dex" data-dtype="Boolean">
                Dexterity            
            
            
                </option><option vaule="Constitution Saving Throw" id="con" data-dtype="Boolean">
                Constitution            
            
            
                </option><option vaule="Intelligence Saving Throw" id="int" data-dtype="Boolean">
                Intelligence            
            
            
                </option><option vaule="Wisdom Saving Throw" id="wis" data-dtype="Boolean">
                Wisdom            
            
            
                </option><option vaule="Charisma Saving Throw" id="cha" data-dtype="Boolean">
                Charisma            
            
        
        </option></select>
    </div>
        <div class="form-group">
            <label>Skill Checks</label>
            <select name="skiCheck" id="skiCheck">
            
                <option label=" "></option>
                
                    <option value="Acrobatics" id="acr" data-dtype="Boolean">
                    Acrobatics
                
                
                    </option><option value="Animal Handling" id="ani" data-dtype="Boolean">
                    Animal Handling
                
                
                    </option><option value="Arcana" id="arc" data-dtype="Boolean">
                    Arcana
                
                
                    </option><option value="Athletics" id="ath" data-dtype="Boolean">
                    Athletics
                
                
                    </option><option value="Deception" id="dec" data-dtype="Boolean">
                    Deception
                
                
                    </option><option value="History" id="his" data-dtype="Boolean">
                    History
                
                
                    </option><option value="Insight" id="ins" data-dtype="Boolean">
                    Insight
                
                
                    </option><option value="Intimidation" id="itm" data-dtype="Boolean">
                    Intimidation
                
                
                    </option><option value="Investigation" id="inv" data-dtype="Boolean">
                    Investigation
                
                
                    </option><option value="Medicine" id="med" data-dtype="Boolean">
                    Medicine
                
                
                    </option><option value="Nature" id="nat" data-dtype="Boolean">
                    Nature
                
                
                    </option><option value="Perception" id="prc" data-dtype="Boolean">
                    Perception
                
                
                    </option><option value="Performance" id="prf" data-dtype="Boolean">
                    Performance
                
                
                    </option><option value="Persuasion" id="per" data-dtype="Boolean">
                    Persuasion
                
                
                    </option><option value="Religion" id="rel" data-dtype="Boolean">
                    Religion
                
                
                    </option><option value="Sleight of Hand" id="slt" data-dtype="Boolean">
                    Sleight of Hand
                
                
                    </option><option value="Stealth" id="ste" data-dtype="Boolean">
                    Stealth
                
                
                    </option><option value="Survival" id="sur" data-dtype="Boolean">
                    Survival
                
            
        </option></select>
    </div>

    <label>DC</label>
    <input type="text" id="dc" name="dc">
    <div style="margin-right:0px;">
        <button type="submit" name="addRollableEvent" value="1" class="addRollable"><i class="fas fa-dice"></i>Add Roll</button>
    </div>
    </fieldset>

    <fieldset>
        <p>Groups give you choices. The same name for group makes you choose between these rolls. Different names for group let's you do both rolls</p>
        <table id="rollableEventsTable">
            <colgroup>
               <col span="1" style="width: 35%;">
               <col span="1" style="width: 20%;">
               <col span="1" style="width: 35%;">
               <col span="1" style="width: 10%;">
            </colgroup>
            <tbody><tr>
                <th style="text-align:left;">Roll</th>
                <th style="text-align:left;">DC</th>
                <th>Group</th>
                <th>Delete</th>
            </tr>
        </tbody>
            <tr id="1599241869093" class="rollableEvent">
                <td><label>Strength Check</label></td>
                <td><label>0</label></td>
                <td><input type="text" id="group" placeholder="group name for rolls"></td>
                <td style="text-align:center;"><a class="item-control training-delete" id="deleteRollable" title="Delete">
                    <i class="fas fa-trash"></i></a>
                </td>
            </tr></table>
    </fieldset>
    <fieldset>
        <label>Add Result</label>
        <label>Start</label>
        <input type="text" id="resultMin" name="resultMin" placeholder="0">
        <label>End</label>
        <input type="text" id="resultMax" name="resultMax" placeholder="5">
        <label>Result Text</label>
        <input type="text" id="resultText" name="resultText">
        <div style="margin-right:0px;">
            <button type="submit" name="addResult" value="1" class="addResult"><i class="fas fa-dice"></i>Add Result</button>
        </div>
        <table id="resultsTable">
            <colgroup>
               <col span="1" style="width: 10%;">
               <col span="1" style="width: 10%;">
               <col span="1" style="width:70%;">
               <col span="1" style="width: 10%;">
            </colgroup>
            <tbody><tr>
                <th style="text-align:left;">Start Value</th>
                <th style="text-align:left;">End Value</th>
                <th>Result</th>
                <th>Delete</th>
            </tr>
        <tr id="1599241885555" class="result">
        <td><label>1</label></td>
        <td><label>10</label></td>
        <td><label>Rolled between 1 and 10</label></td>
        <td style="text-align:center;"><a class="item-control training-delete" id="deleteResult" title="Delete">
            <i class="fas fa-trash"></i></a>
        </td>
      </tr><tr id="1599241895975" class="result">
        <td><label>11</label></td>
        <td><label>99</label></td>
        <td><label>Rolled more than 10</label></td>
        <td style="text-align:center;"><a class="item-control training-delete" id="deleteResult" title="Delete">
            <i class="fas fa-trash"></i></a>
        </td>
      </tr></tbody></table>
        <label>Activity Type</label>
        <input type="radio" id="succFailActivity" name="activityType" value="succFail" checked="checked">
        <label for="succFailActivity">Success/Fail Count</label>
        <input type="radio" id="categoryActivity" name="activityType" value="categories">
        <label for="categoryActivity">Categories</label>

    </fieldset>
    <fieldset>
        <label>Complications</label><br>
        <label>Chance of occuring per use</label>
        <select name="compchance" id="compchance">
            <option label=" "></option>
                <option value="10" id="10">10%</option>
                <option value="25" id="25">25%</option>
                <option value="50" id="50">50%</option>
                <option value="75" id="75">75%</option>
                <option value="100" id="100">100%</option>
        </select><br>
        <label>RollTable to use</label>
        <select name="Complications" id="complications">
            <option label=" "></option>
                <option value="IlUXmc13XqCU9gI5" id="IlUXmc13XqCU9gI5">1,000 gp Gemstones</option>
                <option value="zJaDuEIlCcPGeaJ1" id="zJaDuEIlCcPGeaJ1">10 gp Gemstones</option>
                <option value="FUNAsKgShlUyncZG" id="FUNAsKgShlUyncZG">100 gp Gemstones</option>
                <option value="ids3ocMPJF5cotqk" id="ids3ocMPJF5cotqk">2,500 gp Art Objects</option>
                <option value="OHnsJjrUp4nbb07X" id="OHnsJjrUp4nbb07X">25 gp Art Objects</option>
                <option value="c2MaN9ySGbTDigSb" id="c2MaN9ySGbTDigSb">250 gp Art Objects</option>
                <option value="xx17M9E4nLgyE0qQ" id="xx17M9E4nLgyE0qQ">5,000 gp Gemstones</option>
                <option value="vYD60ZpmRRGN1Svr" id="vYD60ZpmRRGN1Svr">50 gp Gemstones</option>
                <option value="Y0RX24f5JEVQdlQm" id="Y0RX24f5JEVQdlQm">500 gp Gemstones</option>
                <option value="JLNLs6VuT4CAXmUW" id="JLNLs6VuT4CAXmUW">7,500 gp Art Objects</option>
                <option value="46bUcL1qyb6AN495" id="46bUcL1qyb6AN495">750 gp Art Objects</option>
                <option value="3kGGsJXcYXAFEr1X" id="3kGGsJXcYXAFEr1X">A Sample Pantheon; Dawn War Deities</option>
                <option value="7VALkKqAN5s7CTBI" id="7VALkKqAN5s7CTBI">Ability Check Proficiency by Class</option>
                <option value="JY1saT8KUnPGzQnG" id="JY1saT8KUnPGzQnG">Ability Checks</option>
                <option value="FuiyKGdTtnjz8K20" id="FuiyKGdTtnjz8K20">Ability Checks; Typical Difficulty Classes</option>
                <option value="O7YdNakfbTu2Hr4I" id="O7YdNakfbTu2Hr4I">Ability Scores and Modifiers</option>
        </select>
    </fieldset>
    <div>

        <button type="submit" name="submit" value="1"><i class="fas fa-dice"></i>Submit</button>
    </div>
</form></section>
</div>`

This is the form context of the HTML (No error popups like it happens when, for instance, you leave certain blank values)

Yes, it is a world downtime.

**Comment by Juanfrank** [comment]
Could it have something to do with the fact that the .js code checks for a null string, when in fact the form is using the "blank" value as " "?
`option label=" "`

**Comment by Ethck** [comment]
Okay, that is not the error, but I have tracked down the error. For some reason I didn't test the wold downtime, but I can tell you that i've been able to replicate it, so I'll have a fix soon.

**Comment by Juanfrank** [comment]
But anyways, going back on the topic (Saves and Skill Checks). For instance, this downtime activity (which I configured before the update) is like this:

![image](https://user-images.githubusercontent.com/2864949/92272216-20816c00-eeb7-11ea-8f49-a2d8f96dfafe.png)

Yet when I roll it from the sheet, it does not trigger the replacement that is usually done for this Module:

![image](https://user-images.githubusercontent.com/2864949/92272300-49a1fc80-eeb7-11ea-80d8-8a0ca2922339.png)

**Comment by Juanfrank** [comment]
> 
> 
> Okay, that is not the error, but I have tracked down the error. For some reason I didn't test the wold downtime, but I can tell you that i've been able to replicate it, so I'll have a fix soon.

It's not working for custom downtimes either, but I'm glad you found the issue 👍 👍

**Comment by Ethck** [comment]
Fixed with commit 3345ed3

**Comment by Ethck** [comment]
@Juanfrank newest update includes a fix for this. Please test, but it will work now.

**Comment by Juanfrank** [comment]
I'll rename this issue to Downtimes not saving, to address the initial issue in another thread. That part is fixed.
