### ISSUE TITLE
[Bug] Other Modules Casuing Saving Throws and/or Skill Checks not working

### ISSUE THREAD

**Issue by Juanfrank** [Ethck/Ethck-s-Downtime-Tracking#12]
Hello.-

Coming from #11 , Ability Checks work fine. However, when using saving throws and/or skill checks, the following behaviour occurs:

- With Saving Throws, there's no output after clicking the dice

![image](https://user-images.githubusercontent.com/2864949/92273254-06e12400-eeb9-11ea-815f-dc3a5ab42658.png)

![image](https://user-images.githubusercontent.com/2864949/92273275-0f395f00-eeb9-11ea-9cd1-98b1ffd6fd53.png)

- With Skill Checks, there's an output, but it's not replaced afterwards according to the result category (using the same template except replacing the STR Save with Acrobatics):

![image](https://user-images.githubusercontent.com/2864949/92273365-342dd200-eeb9-11ea-8948-911c62297c21.png)

Expected behaviour is, of course, triggering the replacement (changed the example to STR Check):

![image](https://user-images.githubusercontent.com/2864949/92273459-63dcda00-eeb9-11ea-9d1d-dbe4c3909016.png)

**Comment by Ethck** [comment]
Looking at the first image, I noticed that you never added the roll to the activity. It is not enough to enter the values into the textboxes, you also have to click the add roll button. Thanks for the detailed log.

**Comment by Ethck** [comment]
After setting up a similar activity though, there is indeed an error. Investigating.

**Comment by Juanfrank** [comment]
> 
> 
> Looking at the first image, I noticed that you never added the roll to the activity. It is not enough to enter the values into the textboxes, you also have to click the add roll button. Thanks for the detailed log.

Oh, I'm sorry, I added it. I pasted the wrong image (In each example I did change it accordingly).

![image](https://user-images.githubusercontent.com/2864949/92273837-1c0a8280-eeba-11ea-9711-a6e06bc5991d.png)

**Comment by Juanfrank** [comment]
Maybe it has something to do with what I said here? https://github.com/Ethck/Ethck-s-Downtime-Tracking/issues/11#issuecomment-687297915

**Comment by Ethck** [comment]
Okay, this should be fixed. New release was also issued.

**Comment by Juanfrank** [comment]
Sorry for reopening this, as it's kind of funky.

- Using a Saving Throws show up two rolls, one from the username (?) and one from the character. Then the success or failure.

![image](https://user-images.githubusercontent.com/2864949/92277753-adc9be00-eec1-11ea-94a6-6260a01628ba.png)

Attempting to expand the second roll does nothing.

Config:

![image](https://user-images.githubusercontent.com/2864949/92277811-cf2aaa00-eec1-11ea-9a05-caf2b3de2e54.png)

- Using an Ability Check roll only shows the roll, but doesn't check for the result:

![image](https://user-images.githubusercontent.com/2864949/92277910-0e58fb00-eec2-11ea-8529-8f169b12d3b6.png)

Config:

![image](https://user-images.githubusercontent.com/2864949/92277940-22046180-eec2-11ea-930b-76e7dfeffffa.png)

**Comment by Ethck** [comment]
So the double roll is correct. It is a blind roll of the DC. With that said, your issue with the persuasion check in this Magic Item Table would be a bug. I'll investigate it.

**Comment by Ethck** [comment]
Additionally, if you send me a screenshot of the console (f12, but hit the console tab. It should not be HTML code at all). That should also help.

**Comment by Juanfrank** [comment]
![image](https://user-images.githubusercontent.com/2864949/92280708-069c5500-eec8-11ea-9237-39093ec28788.png)

**Comment by Juanfrank** [comment]
![image](https://user-images.githubusercontent.com/2864949/92280777-2c295e80-eec8-11ea-821d-3542a68691a3.png)

**Comment by Ethck** [comment]
Perfect! Was this the only error shown?

**Comment by Ethck** [comment]
Hmm, when did you make this downtime activity?

**Comment by Juanfrank** [comment]
These are the only errors shown from the beginning to the end of the roll button.

**Comment by Juanfrank** [comment]
> 
> 
> Hmm, when did you make this downtime activity?

Pretty much before making the first issue report.

**Comment by Ethck** [comment]
If you roll the event again, is there a new error message?

**Comment by Juanfrank** [comment]
After changing the above examples' check to "Persuasion", the same behavior repeats.

![image](https://user-images.githubusercontent.com/2864949/92281136-fcc72180-eec8-11ea-9061-cd7181540b67.png)

![image](https://user-images.githubusercontent.com/2864949/92281169-0a7ca700-eec9-11ea-92b0-d2b9b25c2cdc.png)

![image](https://user-images.githubusercontent.com/2864949/92281314-4ca5e880-eec9-11ea-9d96-3ab4d0c7b4e5.png)

**Comment by Juanfrank** [comment]
![image](https://user-images.githubusercontent.com/2864949/92281872-8cb99b00-eeca-11ea-9fc5-cfe898062558.png)

I don't know if this might help

**Comment by Ethck** [comment]
Yes, that does help...

**Comment by Ethck** [comment]
My theory is that there is an issue with the Obsidian character sheets.

**Comment by Ethck** [comment]
And it's not... Can you try disabling every other module?

**Comment by Juanfrank** [comment]
Now it triggers, but it's like categories aren't even there 

![image](https://user-images.githubusercontent.com/2864949/92282741-41a08780-eecc-11ea-8336-e93dac65cef1.png)

![image](https://user-images.githubusercontent.com/2864949/92282790-5a10a200-eecc-11ea-8e11-1f9d7c49c9ff.png)

**Comment by Ethck** [comment]
What did you change?

**Comment by Juanfrank** [comment]
I disabled all my modules.

**Comment by Ethck** [comment]
Huh. Could you try to figure out what module caused the issue? Also, can you make a roll without that +22 modifier?

**Comment by Juanfrank** [comment]
Ok I have some modules off and it's working now. I'm on it.

**Comment by Juanfrank** [comment]
Ok, it was the Skill Customization for D&D5e Module: 

https://foundryvtt.com/packages/skill-customization-5e/

Please allow me to facepalm as I walk away.

**Comment by Ethck** [comment]
I can look into making compatibility for this, if you desire.

**Comment by Juanfrank** [comment]
I don't think it's worth it but I appreciate the gesture, haha.

I'm still having issues with it recognizing ranges. I'll delete the last entry and see if it works.

Thanks!

**Comment by Ethck** [comment]
That was actually a bug with the formula. It is fixed in development now, but the next release is going to be over the weekend.
