### ISSUE TITLE
[suggestion] naked roll

### ISSUE THREAD

**Issue by turboraton** [Ethck/Ethck-s-Downtime-Tracking#16]
Hello there Ethck! Many thanks for your great module, I just wanted to request something, do you think it would be possible to roll a naked d20?

**Comment by Ethck** [comment]
Greetings! A naked roll is certainly possible, but I'm struggling with where to put it. I can't exactly just throw it into the existing categories, but I'm also not sure if it deserves it's own roll. Any suggestions? Currently I'm thinking of adding a row titled "Special" and include a couple of other types of rolls in there (perhaps like hit die?), but I'm not sure what all to include.
