### ISSUE TITLE
[Suggestion] Allow complications to be visible to GM only.

### ISSUE THREAD

**Issue by Pyroman2xxx** [Ethck/Ethck-s-Downtime-Tracking#17]
Great mod.

Some complications need to be GM only since they are setups for role-play opportunities that the PC should not see.

In other cases, though, it makes a fun bonus for PCs to see the results of a complication.

Maybe it could be a switch per downtime activity? Kind of how you have private rolls.

**Comment by Ethck** [comment]
So, just to be sure. If a private complication is desired, then the complication should only be messaged to the GM? Do you see any reason why this couldn't be implemented into the current private rolls button?

**Comment by Pyroman2xxx** [comment]
> If a private complication is desired, then the complication should only be messaged to the GM?
Yes, my preference would be to have the results be visible to everyone (no private) but if a complication arises, have that whispered to GM only.

> Do you see any reason why this couldn't be implemented into the current private rolls button?
I think the main thing I am suggesting is a separation of the results from the complications so that the complications could be whispered to the GM.

**Comment by Ethck** [comment]
Okay, I understand that now. I think this is a good addition, so it'll be in the next release. It'll have a similar checkbox to "private Results".
