### ISSUE TITLE
[Bug] Doesn't work with Skill Customization for D&D5e mod.

### ISSUE THREAD

**Issue by GvosRamsey** [Ethck/Ethck-s-Downtime-Tracking#18]
Skill Check rolls will not trigger result messages when using Skill Customization mod.

**Comment by Ethck** [comment]
The Skill Customization mod redoes the core roll functionality of the 5e system (which I use), so that's why this isn't working. I'll look into seeing how to make this work.

**Comment by Ethck** [comment]
This is implemented in https://github.com/Ethck/Ethck-s-Downtime-Tracking/commit/c78aaf4d11cce0c4fd0eebdd283c86512fe88c08. Apologies for the delay.
