### ISSUE TITLE
Suggestion: Allow bonuses for non-skill rolls

### ISSUE THREAD

**Issue by TacoSupreme** [Ethck/Ethck-s-Downtime-Tracking#21]
I love when it asks to make like a persuasion check it pops up a roll dialog allowing advantage/disadvantage and a numerical bonus.

I wish it would also do that for arbitrary die rolls that aren't attached to a skill.  Like if I have a downtime task where they roll 1d100, but I want them to be able to get bonuses by spending extra money it would prompt them to add a bonus like it does with a skill.

**Comment by Ethck** [comment]
Apologies for not responding to this sooner. I got caught up at work and haven't had much time to work with Foundry as of late. Under the hood these two rolls are done extremely differently, namely any "skill" checks are done by the D&D5e system, but the arbitrary die rolls are done custom. I will look into implementing this though.

**Comment by Ethck** [comment]
This is implemented as of https://github.com/Ethck/Ethck-s-Downtime-Tracking/commit/856ba177654e336a38ac2324d9297e06e322a737. Will be in the 0.3.0 release coming soon!

**Comment by TacoSupreme** [comment]
Thanks for the improvement Ethck, it will be a while before my next downtime break where I will need to use it.
