### ISSUE TITLE
0.7.x Double UI Tabs

### ISSUE THREAD

**Issue by akrigline** [Ethck/Ethck-s-Downtime-Tracking#22]
![image](https://user-images.githubusercontent.com/7644614/96348003-b6daad00-1073-11eb-9cfa-439dc44d9a3c.png)

Core Version 0.7.4
dnd5e Version: 0.98
Module Version: 0.2.6 (Fresh Install)

I believe this has to do with the Hook changes in 0.7.x. An extended class runs all of the hooks of the inheritance tree or some such, here's a post from the [League of devs](https://discord.gg/kSAeRF) discord talking about the issue:
![image](https://user-images.githubusercontent.com/7644614/96348107-3cf6f380-1074-11eb-8a7d-84946a1a9730.png)

**Comment by Ethck** [comment]
Wow, thanks for this detailed issue report. I'll look into it, and it is likely the cause. I'll have to fire up my old 0.7.X instance and see if I can get it to work.

**Comment by Ethck** [comment]
After trying to reproduce this issue, I can't seem to reproduce it. My guess is that you are using an old version of Crash's, so please make sure that is updated @akrigline

**Comment by Ethck** [comment]
I tested on:
Foundry v0.7.4
D&D 5e v0.98
Ethck's Downtime v0.2.6
Crash's Downtime v0.4.7

**Comment by akrigline** [comment]
I double checked but I do not have Crash's activated. Should I?

![image](https://user-images.githubusercontent.com/7644614/96480466-41541580-1208-11eb-8615-ea6bbf6ef015.png)

**Comment by akrigline** [comment]
Feel free to ping me on discord @Calego#0914

**Comment by akrigline** [comment]
Further refined Repro steps:
- With only Ethck's enabled, and Crash's disabled
1. Create new Character
2. Observe

Closing and Reopening that character will fix itself.

**Comment by Ethck** [comment]
I can't seem to find out why/how to actually fix this, but the issue seems to fix itself. Closing, thanks for the report(s).

**Comment by Ethck** [comment]
Turns out this was still causing problems, but it's truly fixed now with bcd4def9
