### ISSUE TITLE
Clear e filter World Log

### ISSUE THREAD

**Issue by rinnocenti** [Ethck/Ethck-s-Downtime-Tracking#26]
be able to clear the worlds downtime log, and filter them

**Comment by Ethck** [comment]
What kind of filters are you wanting? By User that did it? By downtime type? As far as clearing the Downtime log, this is already achievable via the console, and I'm not sure I want to allow deletion by an easier method. What use case are you thinking of for deleting being an easy thing to do?

**Comment by rinnocenti** [comment]
Filters by:

- Downtime Type 
- Concluded/Not concluded

I understand the concern with the logs.
however when I'm testing downtime as a GM the log is full of test rubbish.
maybe a button to reset the log (clean for start) on the GM settings screen

**Comment by Ethck** [comment]
Would you want this on a per actor basis, or global?

**Comment by rinnocenti** [comment]
per actor I believe that just filtering by type and by clonclusion is enough, to remove the log for testing purposes, just remove it from the actors, and for the "official" actors it is good to have the complete record.

the global ones are more problematic because it fills of garbge very fast.

**Comment by Ethck** [comment]
Completed with https://github.com/Ethck/Ethck-s-Downtime-Tracking/commit/7a7b61fad19aa462b300e28ef8a25ee5e90dfaab. Please see Commands in the examples to clear old data.
