### ISSUE TITLE
Export not working in 7.5

### ISSUE THREAD

**Issue by rinnocenti** [Ethck/Ethck-s-Downtime-Tracking#27]
export create a empty file.

**Comment by Ethck** [comment]
Export only works with world level downtime activities. Can you please post some screenshots about what you're seeing?

**Comment by rinnocenti** [comment]
![image](https://user-images.githubusercontent.com/3178127/97094493-78249400-162b-11eb-91bf-71ce53e392f0.png)
![image](https://user-images.githubusercontent.com/3178127/97094499-8377bf80-162b-11eb-8050-c2b509694c2c.png)

**Comment by rinnocenti** [comment]
the same happens if I export through settings

**Comment by Ethck** [comment]
Please issue the following command inside the console:
`game.settings.get("downtime-ethck", "activities");`
It's output should be an array with stuff like so:
![image](https://user-images.githubusercontent.com/44616794/97109918-5ced6f00-1693-11eb-959a-52c5893cb727.png)

**Comment by rinnocenti** [comment]
they show
![image](https://user-images.githubusercontent.com/3178127/97110997-03993600-16bb-11eb-9467-8ef348ba6c02.png)
but not in export file.

**Comment by Ethck** [comment]
Can you think of anything that changed between the non-working stage and now?

**Comment by rinnocenti** [comment]
Nothing changed. I haven't updated anything.
before applying the command on the console it still gave undefinid file.
then it worked.
maybe it's related to 1x time generating the array
