### ISSUE TITLE
Suggestion: change "Private Roll" to "Private GM Result" & "Private Complication" to "Blind GM Complication" instead

### ISSUE THREAD

**Issue by Silvestrae** [Ethck/Ethck-s-Downtime-Tracking#35]
Private is a little ambiguous, blind is clearer.

**Comment by Ethck** [comment]
While I can agree that private does not necessarily convey a clear meaning, these options are labeled as such to align with their Foundry roll modes as found here: https://foundryvtt.com/article/dice/

Importantly, private rolls allow the player & the GM to see it, while blind rolls only allow the GM to see it. At this point, I believe sticking to the Foundry terms might be the best route to go, but I'm open to suggestions.

**Comment by Silvestrae** [comment]
Yes that is my point though.. It's not clear because it's all doing different stuff not aligning with foundry roll modes. 

The options in a tasks set up are called 'Private Roll' and 'Private Complication' which one would assume should both allow GM and Player can see... 

Problem 1 however is when 'Private Roll' " is checked, the players skill rolls are output as public (or whatever default roll mode they have selected) ignoring the private roll option in the module. Only the final task result is kept private. If that can't be overridden, perhaps rename the option to say "Private GM Result" so it's clear that it doesn't inude the skill checks. 

Problem 2 is that when "Private Complication" is checked, the complications are output as BLIND and the player cannot see them, only the GM. Hence that option is labelled as 'private' wrong because they are in fact output as 'blind', and Should be labelled as "Blind GM Complication" if that is the intention.

**Comment by Ethck** [comment]
My bad for glossing over the issue. I definitely see the problems now. Reopening and I'll but it back on the todo list. Thanks for being able to explain more!

**Comment by Silvestrae** [comment]
No partially my bad, I was on an issue writing spree at the time and looking at the original post I didn't write the issue with much clarity to begin with 😆
