### ISSUE TITLE
Suggestion: Auto deduct gold

### ISSUE THREAD

**Issue by Silvestrae** [Ethck/Ethck-s-Downtime-Tracking#39]
The use materials prompt is perhaps a little broad as the only material downtime uses is time, and a gold value which represents all resources and sundries the character needs to provide. 

Perhaps have it instead as a gold spent box that data validates an entered numerical value, and takes that value away from the user's gold total.

If you can make it work with the Lazy Money module which auto converts coin denominations, it would be very user friendly.

**Comment by Ethck** [comment]
As much as this feature sounds enticing, I do NOT want to touch actor inventory (especially currency) due to the sheer number of things that can go wrong. Additionally, this module supports a generic interface for downtimes, so there's no way to guarantee that the material used is in gold pieces.
