### ISSUE TITLE
How would I track the building of a Temple...

### ISSUE THREAD

**Issue by jseaz73** [Ethck/Ethck-s-Downtime-Tracking#45]
Temple  -- 50,000 go and 400 days ... 10 hired skilled labor ... 10 unskilled

how would I track the time and the consumption of gold ... etc  or paying the laborers ?

**Comment by Ethck** [comment]
I am terribly sorry for not seeing this earlier. For some reason my notifications did not alert me to your question. I hate to say it, but this task would be much better suited for the Crash's Tracking and Training module. This downtime module is more about repeatable events as opposed to tracking progress between events (what Crash's TNT is explicitly made for).
