### ISSUE TITLE
Suggestion: Betterrollsfor5e compatibility

### ISSUE THREAD

**Issue by Ikabodo** [Ethck/Ethck-s-Downtime-Tracking#51]
Would be super nice if this module could detect [betterrollsfor5e](https://github.com/RedReign/FoundryVTT-BetterRolls5e) and use those instead of "normal" rolls for skills.

**Comment by Ikabodo** [comment]
![image](https://user-images.githubusercontent.com/7766890/108815907-8244a800-75b5-11eb-879c-c2f1a032666c.png)
Without vs With Betterrollsfor5e

**Comment by Ethck** [comment]
I have a semi-working version that I just posted on the develop branch (commit 0f931c0), but I'll have to do more testing before I can release it. Thanks so much for the idea!
