### ISSUE TITLE
Error with BetterRolls + Midi QOL compatibility

### ISSUE THREAD

**Issue by Ikabodo** [Ethck/Ethck-s-Downtime-Tracking#55]
I'm getting an error `Uncaught (in promise) TypeError: Cannot read property 'altKey' of undefined` when having betterrolls compatibility active. 

Maybe there was a change somewhere? it worked before one of the recent updates.

**Comment by Ethck** [comment]
Is there any more to this error? Like a line number or a file name? the `altKey` property is not used by this module but is used by BetterRolls and it seems like it is expecting that property to be somewhere when it isn't...

**Comment by Ikabodo** [comment]
![image](https://user-images.githubusercontent.com/7766890/110674369-1d529a00-81d2-11eb-8d0a-6e37e32f06cb.png)

**Comment by Ethck** [comment]
Perfect! When you roll this to cause an error, are you holding down the altKey or not?

**Comment by Ethck** [comment]
I can't seem to reproduce this. Can you try to determine the sequence of events that you do to cause this error?

**Comment by Ikabodo** [comment]
I narrowed it down to a conflict with midiqol for some reason (!?). Let me look around some more.

**Comment by Ethck** [comment]
@Ikabodo I still can't seem to reproduce this, and looking at Midi's code it *appears* that it may have been solved. Can you double check if this is still an issue? Thanks!

**Comment by Ikabodo** [comment]
Yeah, I can't reproduce it any longer either. Not sure what caused it. Sorry for the trouble!
