### ISSUE TITLE
There is no way of hiding an activity from players.

### ISSUE THREAD

**Issue by TiagoFrossard** [Ethck/Ethck-s-Downtime-Tracking#57]
I wish I could create an activity and keep it hidden until it is the right time to reveal it to the players. As the module runs now, twhenever you previously prepare activities, they get spoiled to the players.

**Comment by Ethck** [comment]
I'm intrigued as to the use case you have in mind here. Can you elaborate how an activity would be secret before hand? I'll look into implementing this in the mean time.

**Comment by TiagoFrossard** [comment]
I can think of some examples of this need:
- You might have a roll for some book or item your players haven't discovered yet and you don't want to spoil it
- You might have a table that's not finished and you want it to be useable only after completion
- You might have a gathering roll to simulate a Monster Hunter/Dauntless mechanic for a boss you don't want to spoil
