### ISSUE TITLE
Not showing the results

### ISSUE THREAD

**Issue by Winter-Tempest** [Ethck/Ethck-s-Downtime-Tracking#59]
So I've gone through the process of making all the rolls and results tables, but when clicking on the icon, it will only show the rolls and not the results.  Am I doing something wrong?

**Comment by Ethck** [comment]
In order to diagnose this, can you post a screenshot of what your activity configuration looks like? Additionally, are you using any of the following modules: Dice so Nice, BetterRolls5e, Midi QOL, or Skill Customization 5e?

**Comment by Winter-Tempest** [comment]
Apologies for the delay.  I don't have any of those modules... I'm guessing I need them?
![modules](https://user-images.githubusercontent.com/83143158/117558357-9420dd80-b031-11eb-9243-c4348f20df8e.PNG)
![Downtime](https://user-images.githubusercontent.com/83143158/117558443-5f615600-b032-11eb-8195-6aceb5b5735d.PNG)

**Comment by Ethck** [comment]
No, you don't need any of those modules, those modules have been known to cause issues in the past so I usually make sure to ask about those specific ones. Thank you for the update and I will attempt to figure this out.
