### ISSUE TITLE
Grouped Rolls Don't Respect Selections

### ISSUE THREAD

**Issue by crash1115** [Ethck/Ethck-s-Downtime-Tracking#6]
**Problem:**
When setting up an activity that gives the user the option to select one of multiple options, the option they select is not respected when the rolls are made. It looks like it's defaulting to the first option.

**Info:**
- Foundry v0.6.6
- DnD5e v0.95
- All modules disabled
- Issue occurs with both player-defined and GM-defined world activities
- Issue occurs when performing activity as both player and GM

**Steps to Reproduce:**

Setup
![image](https://user-images.githubusercontent.com/41387713/92011037-81267280-ed18-11ea-86ce-f4c433a50502.png)

Dialog (note Cha is selected)
![image](https://user-images.githubusercontent.com/41387713/92011093-93081580-ed18-11ea-96e1-80a38fbef566.png)

Roll outcome (Con gets rolled)
![image](https://user-images.githubusercontent.com/41387713/92011163-adda8a00-ed18-11ea-9c0b-49111c33b00e.png)

**Comment by Ethck** [comment]
Thanks for the extremely detailed report. I am investigating this now.

**Comment by Ethck** [comment]
Hmm, this is actually happening... rip. I'll have a fix out shortly.

**Comment by Ethck** [comment]
Fixed. Will push a new release now.
