### ISSUE TITLE
Downtime Activity tab no longer shows up on sheet

### ISSUE THREAD

**Issue by Aritei** [Ethck/Ethck-s-Downtime-Tracking#61]
As of 01.05.2021 I noticed that the downtime activity tab was suddenly gone. It just doesn't show anymore, no matter what I do.

This was also tested with a fresh world and no other modules activated.

**Comment by Ethck** [comment]
I can not seem to replicate this. Can you double check what version of Foundry and what version of this module you are using? Additionally, please check the Console (f12 -> Console) to see if there are any errors when you attempt to access the downtime tab.
