### ISSUE TITLE
[Bug] All custom formulas count as 'broken'

### ISSUE THREAD

**Issue by GeneralDisorder** [Ethck/Ethck-s-Downtime-Tracking#63]
I recently tried creating a world downtime activity with a custom formula skill check, but regardless of the custom formula's content, it throws an error that the custom formula is 'invalid' and doesn't save the activity.

The formula I want to use is: 1d20 + @abilities.wis.mod + @attributes.prof
But simpler formulas such as just "1d20" or "1" are also rejected.

![DowntimeError](https://user-images.githubusercontent.com/8729203/125682268-8ae6a8a7-07ab-4746-9a8e-a8915a3fc292.PNG)

Foundry version 0.8.8
Downtime tracking version: 0.5.0

**Comment by Ethck** [comment]
Thank you for reporting this. Based on the error it appears to be failing because it can not find your actor's class hit die (used for some extra roll parameters). The lack of an actor hit die is an oversight on my part, but that should at least allow you to fix this error.

**Comment by Ethck** [comment]
I stand corrected, this was an error with the new data model in the newer versions of the D&D system that I apparently hadn't tested. Fixed with c93f6609.
