### ISSUE TITLE
Bug: Compatibility Mode with Crash's is broken

### ISSUE THREAD

**Issue by crash1115** [Ethck/Ethck-s-Downtime-Tracking#64]
I overhauled my UI during my 0.8.x updates, and now with both mods enabled and the compatibility mode on, things... break.

My tab, compatibility option off:
![image](https://user-images.githubusercontent.com/41387713/126857472-257c45d8-03d1-446f-94d1-526c21894cf9.png)

Shared tab, compatibility option on:
![image](https://user-images.githubusercontent.com/41387713/126857448-1efa3a77-bfde-4626-930e-5d934463ce7d.png)

Stuff that's wrong:
- Any of my items that live in categories get shunted back to the default one rather than displaying in their appropriate places.
- Your stuff just kinda lives right below the default category rather than under all of them

I haven't really picked at it, but I'm guessing your wrapping / unwrapping is no longer hitting the expected location because I totally reworked the page structure when I built categories into my module.

One UX / clarity thing that might be worth looking at when this gets fixed is to add some kind of separation between the two things that inhabit the shared tab. I have buttons and stuff that live above my item lists, and without some sort of dividing line, it's not immediately apparent they belong to my stuff and have nothing to do with yours.

**Comment by Ethck** [comment]
It ain't super pretty but I fixed it up and added some significant spacing.
![image](https://user-images.githubusercontent.com/44616794/126873744-20947fda-7d6b-4da5-a9fa-d6d4e8c02a36.png)

Closed with 9d893a4
