### ISSUE TITLE
Bug report regarding Importing and Suggestion

### ISSUE THREAD

**Issue by turboraton** [Ethck/Ethck-s-Downtime-Tracking#65]
Hey there Etchk, first of all let me thank you for your WONDERFUL module! 

First of all I wanted to report a bug: when you import, the categories don't remain and it puts them all into uncategorized 
![image](https://user-images.githubusercontent.com/70917100/127782002-bc5f6513-9916-41ee-9e26-03b5c0411da7.png)

Lastly. As you can see I'm using your amazing module to track reputation for my players and the different factions they encounter. I was wondering that if you could include a threshold mechanic where for example, if it reaches a % of the progress, something happens (just a text display or a change of colour of the progress bar is more than enough for me).

Many thanks again and have a good day!

**Comment by Ethck** [comment]
Greetings @turboraton ! Thank you for using Github to reach out; however, your bug/suggestion is actually for Crash's Tracking and Training. I will let Crash know, but suggest that you post this over on their Github page.
