### ISSUE TITLE
Better Rolls Compatibility Broken (Again)

### ISSUE THREAD

**Issue by Ethck** [Ethck/Ethck-s-Downtime-Tracking#66]
Reported by Ketara on 08/07/2021

> While Better Rolls is enabled any activity that has you choose between different skill options will fail.

**Comment by Ikabodo** [comment]
Yeah, getting some strange behaviour here too. If I roll a simple skill check the roll shows up, but the actual chat card wont show up until i roll ANOTHER roll that has groups active.

A simple activity.
![image](https://user-images.githubusercontent.com/7766890/129171140-f6ca1331-8377-4c0d-ac1a-961023abec0c.png)

Here you can see that the cards show up together when the second activity was rolled.
![image](https://user-images.githubusercontent.com/7766890/129171225-5229ea12-ac8b-4b7f-97c9-8d3def3cd0ef.png)

**Comment by Ethck** [comment]
Thanks so much for the pictures @Ikabodo ! They help tremendously; however, I can't seem to replicate this. Can you please ensure that you are using v1.6.7 of BetterRolls5e (newest version and the one I just tested on).

**Comment by Ikabodo** [comment]
Thanks to the wonderful find the culprit I have identified the issue.

It's caused by Dice so Nice actually (kinda surprised me). Especially if the setting "display chat message immediately" is not set.

I think the default dice so nice setting is to have the chat card delayed until the dice is rolled, I guess this causes a conflict with your card.

**Comment by Ethck** [comment]
Original issue fixed, but new issue arisen. I will look into it, thanks for the insight!

**Comment by Wade0004** [comment]
This may be related... There is a issue with the skills.  If I turn this hunting from a survival check to a Brewer's Supply, it works just fine. (first pic)

Also, if i turn off Dice so Nice (disable the mod) then it will indeed post the chat icon, and say that the downtime activity was completed, but it won't roll the table (2nd pic)

![image](https://user-images.githubusercontent.com/74107522/129506492-9240ac35-d650-459c-9d75-eda8aaebd194.png)

![image](https://user-images.githubusercontent.com/74107522/129506646-c1d7fcdc-4957-4acb-aa88-cf7e40ef1454.png)

**Comment by Wade0004** [comment]
The first rolls with the Brewer's Supplies were WITH dice so nice activated.

**Comment by Wade0004** [comment]
Sorry, here's another one...  Advantage seems not to be working with Better Rolls either.  In this one it took the 15 not the 25

![image](https://user-images.githubusercontent.com/74107522/129507065-5f7b60c0-b012-4755-962c-170b58923c86.png)

**Comment by Ethck** [comment]
Dang, thought for sure I had made sure that was okay... Guess not! I'll have to ponder about how to work with advantage/disadvantage because as it stands I have no idea if you're doing it with either. Based on your pictures and descriptions it seems as though there are some issues with the way I'm matching against Survival, so I'll take a look. Thanks for the bug reports y'all!
