### ISSUE TITLE
Exception generated when opening actor in a compendium

### ISSUE THREAD

**Issue by earlSt1** [Ethck/Ethck-s-Downtime-Tracking#71]
```
training.js:158 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
[Detected 2 packages: downtime-ethck, lib-wrapper]
    at addTrainingTab (training.js:158)
    at training.js:517
    at Function._call (eval at <anonymous> (libWrapper-consts.js:9), <anonymous>:4:14)
    at Function.call (foundry.js:179)
    at Tidy5eNPC._render (foundry.js:2097)
    at async Tidy5eNPC._render (foundry.js:2729)
```
When I open an actor in a compendium, the module tries to add the training tab to the sheet, but it's trying to use the actor information in the world.  I dont think it's breaking anything, but having the error in the console made me realise what was happening.

From a cursory glance if you add a check here to see if the actor exists, and if it doesn't just returning out of the function, it should work (I havent had a look through all the code just the bit where its generating an exception): https://github.com/Ethck/Ethck-s-Downtime-Tracking/blob/54cf1406bb7acef21bfd196a3cde7814b644f1d3/training.js#L155-L159

**Comment by Ethck** [comment]
Huh, that's odd! I'll look into it. Thanks for the suggestion & report.
