### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by CaosFR** [Ethck/Ethck-s-Downtime-Tracking#73]
Hi,

Thanks for yourr cool mod :) 
I would like to know if I can translate your mod in french and how I can do that neatly (for sharing my work to you).

If some translate had already starting I can help.

**Comment by Ethck** [comment]
Apologies for taking a while to respond. At this time there is no method for translation; however, this is likely something I should implement. When I find the time I will be sure to let you know! Thanks for offering your help!
