### ISSUE TITLE
[FEATURE REQUEST] Recipe/Blueprint System

### ISSUE THREAD

**Issue by justinthejaguar** [Ethck/Ethck-s-Downtime-Tracking#74]
Would it be possible to:
- Allow pre-made blueprints for weapons and consumables?
- Allow the downtime roll to consume material/gold
- Allow successful multiples to add a linked item to the player's inventory.

**Comment by Ethck** [comment]
I'm not entirely sure what you mean by "pre-made blueprints for weapons and consumables". Could you explain that a bit more?
Currently you can set for materials to be listed as "consumed" but it doesn't actually consume them, I can work on that for the next update.
Are "successful multiples" multiple uses of the same Downtime, or just if you exceed the DC for all groups, add an item?

Overall, more explanations would help me understand what you want.

**Comment by justinthejaguar** [comment]
> I'm not entirely sure what you mean by "pre-made blueprints for weapons and consumables". Could you explain that a bit more? Currently you can set for materials to be listed as "consumed" but it doesn't actually consume them, I can work on that for the next update. Are "successful multiples" multiple uses of the same Downtime, or just if you exceed the DC for all groups, add an item?

Pre-made Blueprints: I'd like it if I could create a library of downtime tasks (not necessarily linked to a specific actor) that can be hidden until the player learns about them. Say a player finds a recipe for a potion of heroism. I'd like to have that prepared prior to them finding it so that I can reveal it once they have the recipe. Similar to giving an actor a feature.

You were spot on on the consumption request. It would be nice if I could say that a task consumes 5 gold a day(or hour) until completed, and when the player completes the roll it subtracts gold.

Successful multiples to add a linked item: What I mean on this one is after the player has had the required number of successful rolls to create the item, I would like it to add the item to the player's inventory. This one could be messy with a lot of variables though, so it might not be worth it.

**Comment by Ethck** [comment]
Well, I have some good news on that front! You are already able to create world level downtime activities (available to all actors in the world). You can do this by using the config menu, or hitting the edit button in the character sheet next to the "World Downtimes" section.

In regards to hiding downtime activities you are able to do that on a per-downtime basis with the "Hidden" checkbox.

Both 2 & 3 deal with removing / adding items to an actor and I should be able to get that to work. One question on your 3rd point though. Is this over multiple invocations of a downtime activity, or just one? Say I've got a research task that has 4 unique and required rolls (so 4 groups). If I succeed on all 4 rolls, will I be granted the item? Or is it based on a "Oh, I got 2 this week, and 3 on my second week. 2 + 3 > 4, so now I get the item?"

Just trying to make sense of it. Let me know.

**Comment by justinthejaguar** [comment]
I was thinking more along the lines of setting a number of rolls, and the player needs to beat DC15 on say two out of the three rolls.

Let me use the well known story of the Crêpes of Stealth.

Fighter Chef Gordan finds the recipe for the Crêpes of Stealth. In order to make the Crêpes of Stealth of stealth, Fighter Chef Gordan must spend three hours completing the recipe, and succeed on at least two of the DC 15 Baker's Tool checks required to make the Crêpes of Stealth. Each hour, one unit of baker's flower consumed. If two rolls are failed, Fighter Chef Gordan's Crêpes of Stealth recipe fails. Otherwise, the Crêpes of Stealth appear in Fighter Chef Gordan's inventory at the end of the third hour. Now Fighter Chef Gordan can eat the Crêpes of Stealth to get advantage on all stealth checks for 24 hours.

**Comment by Nhaaro** [comment]
I'm also interested in this, I have an alchemist player who could benefit a lot from this

**Comment by justinthejaguar** [comment]
The last of these seem to be achievable with the success count option. I've found myself less inclined to have items granted through automation with more experience with Foundry. The comment has been around for a while, so I am closing it.
