### ISSUE TITLE
problems with the result list

### ISSUE THREAD

**Issue by rinnocenti** [Ethck/Ethck-s-Downtime-Tracking#75]
in the last version for v9 the result list is not being saved, and the ones that existed are not being displayed correctly.
some disappear with half the list others with the complete list.

apparently if the complications box is not checked it does not save the contents of the line or disappears with those that were not previously.

**Comment by Ethck** [comment]
Somehow I missed this bug report, my apologies. It's odd that it doesn't work, but I'll get a fix made and published today.
