### ISSUE TITLE
[Bug] Tool Check instrumental not work

### ISSUE THREAD

**Issue by rinnocenti** [Ethck/Ethck-s-Downtime-Tracking#77]
![image](https://user-images.githubusercontent.com/3178127/152475810-0f842b8a-96c7-4df6-b731-1afe8fc352c8.png)
![image](https://user-images.githubusercontent.com/3178127/152475834-561ce972-8a1f-495b-ad32-77cc34890b4d.png)

can't find any kind of instrument

**Comment by Ethck** [comment]
Apologies for the delay on this. This is caused by the Tool not having the word "Instrument" in it. I'll spend some time making a better method to solve this.
