### ISSUE TITLE
"Success Count" type activities fail with non-trivial DCs

### ISSUE THREAD

**Issue by Akaito** [Ethck/Ethck-s-Downtime-Tracking#78]
If the DC is set to a static number, like "5", that works.  If the DC is set to a simple roll, "1d6", that also works.
But if you try to add anything, say to match Xanathar's downtime activity DCs (2d10+5), then this module always acts as if there were 0 successes.  Currently using Foundry VTT v9.249.
![image](https://user-images.githubusercontent.com/6599279/155497916-de6626e6-ee9a-4288-94e4-fca727883489.png)

**Comment by Ethck** [comment]
I haven't recently modified anything in this area, so I'm initially unsure of what could cause this. I'll look into it. Thanks for reporting it!

**Comment by Ethck** [comment]
I've been able to verify that these complicated terms are indeed suddenly returning `undefined` when rolled, should be able to find a fix today.

**Comment by Ethck** [comment]
Looks like the change is based on `Roll.toMessage()` being an async function, and for some reason I was not `await`ing it. That has been fixed and solves the problem as seen in this depiction: 
![image](https://user-images.githubusercontent.com/44616794/156077685-d24380ba-7bc8-4a71-9d6d-ef1218678c96.png)
