### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by AgentSells** [Ethck/Ethck-s-Downtime-Tracking#84]
Is it possible to get this to hook on any time a player character does a skill check?

I know this is not a core mechanic but I think it would be a really positive feature

i.e. a party that spends a lot of time in the wilderness may constantly be doing survival or nature checks, after a certain threshold of success is met you might want to give the characters proficiency or even eventually expertise in that skill. To reflect that they are learning skills while adventuring not just in downtime.

The same will go for things like lock picking using certain tools etc etc

I think this would be a very fruitful way to ad dept to a long-term game.

It is literally an embodiment of the phrase "practice makes perfect"

**Comment by Ethck** [comment]
Possible? Sure, but that is out of the scope of this module.
