### ISSUE TITLE
DND5e 2.2.2 has changed how skills and abilities are stored

### ISSUE THREAD

**Issue by ctbritt** [Ethck/Ethck-s-Downtime-Tracking#85]
I think the updates to DnD5e have broken this module. None of the skills show up, showing just `[object object]` and none of the saving throws or abilities checks stick, reverting to `Strength`. Screen shots:

![CleanShot 2023-07-26 at 14 48 11@2x](https://github.com/Ethck/Ethck-s-Downtime-Tracking/assets/4516034/486b3e44-6279-4e1f-81a9-aaaf8bc4e2d5)
Messed up skill selection

![CleanShot 2023-07-26 at 14 48 44@2x](https://github.com/Ethck/Ethck-s-Downtime-Tracking/assets/4516034/95f2244b-d8cb-49c0-a64b-6435f956d6df)
Trying to set ability check and saving throw

![CleanShot 2023-07-26 at 14 48 52@2x](https://github.com/Ethck/Ethck-s-Downtime-Tracking/assets/4516034/4dafb293-f13e-4d47-bff9-c56431df4556)
After I hit `submit`

This is on foundry 11.306 and DnD5e 2.2.2

**Comment by AndreCaseyScott** [comment]
I can confirm this issue. I cannot set up any rolls using the skills and abilities shown in the dropdown, as they all default to "Strength". I also cannot set the skills manually using the "@abilities.str.mod" type format. 

Looking forward to a fix on this. Thanks.

**Comment by justinthejaguar** [comment]
Issue remains.
FVTT V11.308
D&D5E 2.3.1
E5DT 0.7.0

**Comment by Ethck** [comment]
Fixed with commit a3bea0f
