### ISSUE TITLE
Bug - Can't choose any tool check

### ISSUE THREAD

**Issue by tirzah2** [Ethck/Ethck-s-Downtime-Tracking#87]
Hi,
If i select Tool i cant' see any tool to choose from the dropdown menu. In particular if i want to create a world activity where i need to choose many different tools. 

I also tried on a token with several tools in the inventory.

**Comment by Ethck** [comment]
Can you screenshot the tools in the actor's inventory? Actor's must have the tool in their inventory in order for it to be available to roll.
