### ISSUE TITLE
feat: Tidy 5e Sheet rewrite compatibility

### ISSUE THREAD

**Issue by kgar** [Ethck/Ethck-s-Downtime-Tracking#90]
Hello, I am working on the Tidy 5e Sheet rewrite, and I recently released an API for adding tabs to the new sheets. I was wondering if we could collaborate on adding compatibility for the new sheets to this module.

The main reason things are likely not to be working is that my sheets have a different approach to tabs, in that I am offering the user tab selection. So, for these sheets, a module registers a tab, and the user / GM can choose which tabs to include or exclude on actor sheets. This is in addition to the sheet class being different from the original Tidy and is subject to change when the sheets leave alpha.

The API for registering tabs begins here: https://kgar.github.io/foundry-vtt-tidy-5e-sheets/classes/Tidy5eSheetsApi.html#registerCharacterTab

Would you be open to some discussion on how to get your and my module working together?

**Comment by Ethck** [comment]
My apologies for not reacting to this sooner, but with the help of your documentation I was able to get it working (as far as I can tell). Please check out the branch feature/EDT-90-tidy5e-rewrite and let me know if you can break anything.

**Comment by kgar** [comment]
Ethck, this is truly awesome. Thank you! 
I will test this tonight (in my CST time zone).
I really appreciate your understanding. These sheets are a different beast, but I am hoping it will be worth the trouble to do this intentional integrating.

**Comment by kgar** [comment]
I was able to test early. I have one recommendation on the tab registration code after testing.
I also have some CSS to release on my side where I was missing compatibility styles. That will go out tomorrow evening.

**Comment by kgar** [comment]
After thinking more about the default sheet listeners topic, I'm going to default activating default sheet listeners to `false` on my side and require opt-in for those who need it. With that, I think your branch looks good to go.

**Comment by kgar** [comment]
Let me know if there's any other info I can provide. Last I looked, it looked good to go.

**Comment by Ethck** [comment]
I merged and released this today as version 0.7.4.
