### ISSUE TITLE
Musical Instruments not working

### ISSUE THREAD

**Issue by NoaDel** [Ethck/Ethck-s-Downtime-Tracking#94]
also Custom formulae arent working, but someone already said that.
We have created a fresh world to test this, but i think the issue might be because instruments are now called musical instruments?

**Comment by Ethck** [comment]
I'll take a look later today.

**Comment by NoaDel** [comment]
oh thanks for responding so fast, thank you. Our group is so excited to use this

**Comment by Ethck** [comment]
I can't seem to replicate any sort of errors with the custom formulas. Here's an example where I was able to roll while adding in the number of platinum pieces on a character.
![image](https://github.com/Ethck/Ethck-s-Downtime-Tracking/assets/44616794/962090c1-b240-46d5-9e47-809502c907a6)
![image](https://github.com/Ethck/Ethck-s-Downtime-Tracking/assets/44616794/bf1e3bb0-24ad-4621-a90c-94363376650c)

On the other hand, I have a fix now for the tools and will push that out later today.

**Comment by Ethck** [comment]
8677b32 should fix this up.
